### PR TITLE
Refactor qmake project files to be easier to maintain

### PR DESCRIPTION
**Pull request by gustavosbarreto**
Hello,

I did this change to be more easier to maintain the qhttp library in our Yocto build system. I hope this may be helpful for other package maintainers.

### CODE REVIEW

**Comment by otavio** [comment]
We did the integration of this onto our Yocto Project-based system and the build works just fine.

@azadkuh please consider to merge this as it avoid us to maintain the fork and help other projects as well.

**Comment by azadkuh** [comment]
Thanks for your help, the PR look so good.
I will merge it asap.

I'm thinking about moving out from `qmake` to `cmake` for `qhttp` as i myself hardly use `qmake`. not sure about other users experience and taste.

**Comment by otavio** [comment]
Please do. CMake is quite good and allows for a wide range of OS support. I think it is a good change.

**Comment by azadkuh** [comment]
rebased and merged into `dev`
thank you @gustavosbarreto

**Pull request closed without merging**
